version: '3.8'

services:
  olist-dbt:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dbt
    container_name: olist-dbt
    hostname: olist-dbt
    restart: unless-stopped
    environment:
      DBT_ALLOW_EXPERIMENTAL_ADAPTERS: "true"
    volumes:
      - ../:/app
    working_dir: /app/dbt_olist
    command: sleep infinity
    networks:
      - bigdata-net

networks:
  bigdata-net:
    external: true
    name: bigdata-net
