name: "olist_dbt"
version: "1.0.0"
config-version: 2

profile: "olist_dbt"

model-paths: ["models"]

models:
  olist_dbt:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: view
      +schema: gold
